org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.71

mod_id=sonblocks
mod_name=Son Blocks
mod_license=AGPL-3.0-or-later
mod_version=1.0.0
mod_group_id=dev.project516.sonblocks